#!/usr/bin/env php
<?php

use Csv2Qif\Command\Convert;
use Parable\Console\App;
use Parable\Di\Container;

/** @var App $app */
/** @var Container $di */
[$app, $di] = require __DIR__ . '/bootstrap.php';

$app->setDefaultCommand($di->get(Convert::class));
$app->run();
