fallback: true
matchers:
    Joint Account In:
        transfer: Income:Joint Account
        description:
            - getNoteDescription
        rules:
            - transfer equals <IBAN of Joint Account>
            - amount greaterThan 0
    Joint Account Ex:
        transfer: Expenses:Joint Account
        rules:
            - transfer equals <IBAN of Joint Account>
            - amount lessThan 0
    Father's House Ministries:
        transfer: Gifts:Father's House Ministries
        rules:
            - description contains Fathers House.Ministries
    Go and Tell Gifts:
        transfer: Gifts:Go and Tell
        rules:
            - description contains Go and Tell
            - notes->authorizationId equals 12345
    ING Costs:
        transfer: Expenses:ING
        rules:
            - description contains Kosten
            - oneOf:
                - notes->description contains ING Bank
                - allOf:
                    - notes->description isEmpty
                    - notes->source contains ING Bank
    Specsavers Contacts:
        transfer: Expenses:Specsavers:Contacts
        rules:
            - description contains Specsavers
            - notes->authorizationId not isEmpty
    Specsavers Glasses:
        transfer: Expenses:Specsavers:Glasses
        rules:
            - description contains Specsavers
            - notes->authorizationId isEmpty
    Oranje Spaarrekening <account_number> Deposit:
        transfer: Assets:Bank:Savings
        description: Deposit
        rules:
            - account equals <Your IBAN>
            - notes->source equals Naar Oranje Spaarrekening <account_number>
    Oranje Spaarrekening <account_number> Withdrawal:
        transfer: Assets:Bank:Savings
        description: Withdrawal
        rules:
            - account equals <Your IBAN>
            - notes->source equals Van Oranje Spaarrekening <account_number>
