#!/usr/bin/env php
<?php

use Csv2Qif\Command\Convert;
use Csv2Qif\Command\Ui;
use Csv2Qif\Command\Validate;
use Parable\Console\App;
use Parable\Console\Command\Help;
use Parable\DI\Container;

require_once __DIR__ . '/vendor/autoload.php';

$cmd = Container::get(Help::class);

Container::get(App::class)
    ->setDefaultCommand($cmd)
    ->setOnlyUseDefaultCommand(true)
    ->addCommands([
        Container::get(Convert::class),
        Container::get(Ui::class),
        Container::get(Validate::class),
    ])
    ->run();
