#!/usr/bin/env php
<?php

use Csv2Qif\Command\Convert;
use Csv2Qif\Command\Ui;
use Csv2Qif\Command\Validate;
use Parable\Console\App;
use Parable\Console\Command\Help;
use Parable\DI\Container;

require_once __DIR__ . '/vendor/autoload.php';

Container::get(App::class)
    ->setName(<<<'NAME'
                  ___         _ ____
  ___________   _|__ \ ____ _(_) __/
 / ___/ ___/ | / /_/ // __ `/ / /_
/ /__(__  )| |/ / __// /_/ / / __/
\___/____/ |___/____/\__, /_/_/
 Help                  /_/
NAME
    )
    ->setOnlyUseDefaultCommand(true)
    ->addCommands([
        Container::get(Convert::class),
        Container::get(Ui::class),
        Container::get(Help::class),
        Container::get(Validate::class),
    ])
    ->setDefaultCommandByName('help')
    ->run();
