#!/usr/bin/env php
<?php

use Csv2Qif\Command\Convert;
use Csv2Qif\Command\Ui;
use Csv2Qif\Command\Validate;
use Parable\Console\App;
use Parable\Console\Command\Help;
use Parable\Di\Container;

/** @var App $app */
/** @var Container $di */
[$app, $di] = require __DIR__ . '/bootstrap.php';

$app->setName(<<<'NAME'
                  ___         _ ____
  ___________   _|__ \ ____ _(_) __/
 / ___/ ___/ | / /_/ // __ `/ / /_
/ /__(__  )| |/ / __// /_/ / / __/
\___/____/ |___/____/\__, /_/_/
 Help                  /_/
NAME
);
$app->addCommands([
    // Keep this list alphabetical by name
    $di->get(Convert::class),
    $di->get(Ui::class), // name is csv2qif
    $di->get(Help::class),
    $di->get(Validate::class),
]);
$app->setDefaultCommandByName('help');
$app->run();
